spring:
  datasource:
    username: cmsadmin
    password: 123456
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cms?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: cmsserver123@gmail.com
    password: cmsserver987
    properties.mail.smtp:
      auth: true
      starttls.enable: true